Check if rules used in authSchema even exists
AstrumU/graphql-authz pull request #74
Opened 2022-08-02 16:08 UTC by kerimcharfi

Here's a quick and dirty POC for #73

2022-08-02 16:09 UTC, XBeg9 requested changes

2022-08-02 16:09 UTC, XBeg9 commented on packages/core/src/config.ts
> +        //@ts-ignore
try to not use ignore

2022-08-02 16:09 UTC, XBeg9 commented on packages/core/src/config.ts
> +          //@ts-ignore
try to not use ignore

2022-08-02 16:09 UTC, XBeg9 commented on packages/core/src/config.ts
> +  if (config.authSchema) {
can you add tests?

2022-08-02 16:09 UTC, XBeg9 commented
please add changesets

2022-08-02 19:57 UTC, kerimcharfi commented on packages/core/src/config.ts
> +  if (config.authSchema) {
sure

2022-08-03 14:20 UTC, kerimcharfi commented
Alright?

2022-09-12 06:27 UTC, XBeg9 approved these changes

2022-09-12 06:27 UTC, merged