Handle error when invalid field is requested
AstrumU/graphql-authz pull request #75
Opened 2022-08-16 23:07 UTC by defond0

Currently if a query is passed to the rules library that references a field that does not exist on schema the call to `getFields` will return undefined and that will cause the next call to `getArgumentValues` to throw the following `TypeError`:
```
Cannot read properties of undefined (reading 'args')
TypeError: Cannot read properties of undefined (reading 'args')
    at getArgumentValues (/Users/jeffreydefond/projects/graphql-authz/node_modules/graphql/execution/values.js:183:28)
    at Object.Field (/Users/jeffreydefond/projects/graphql-authz/packages/core/src/rules-compiler.ts:290:27)
    at Object.enter (/Users/jeffreydefond/projects/graphql-authz/node_modules/graphql/utilities/TypeInfo.js:387:27)
    at visit (/Users/jeffreydefond/projects/graphql-authz/node_modules/graphql/language/visitor.js:200:21)
    at compileRules (/Users/jeffreydefond/projects/graphql-authz/packages/core/src/rules-compiler.ts:346:3)
    at Object.requestDidStart (/Users/jeffreydefond/projects/graphql-authz/packages/plugins/apollo-server/src/index.ts:26:29)
    at initializeRequestListenerDispatcher (/Users/jeffreydefond/projects/graphql-authz/node_modules/apollo-server-express/node_modules/apollo-server-core/src/requestPipeline.ts:598:39)
    at processGraphQLRequest (/Users/jeffreydefond/projects/graphql-authz/node_modules/apollo-server-express/node_modules/apollo-server-core/src/requestPipeline.ts:115:28)
    at ApolloServer.executeOperation (/Users/jeffreydefond/projects/graphql-authz/node_modules/apollo-server-express/node_modules/apollo-server-core/src/ApolloServer.ts:995:33)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```
This PR adds tests to replicate this error, and updates `visitWithTypeInfo` to return undefined when we find that `getFields` on the partentType has returned undefined.

2022-08-29 16:29 UTC, defond0 commented
Is there a different way that we would like this done? We could potentially work on a fix around changing how the plugin handles these validation errors when it is first given the query.

2022-09-08 13:26 UTC, OoDeLally commented
I'd love this to be addressed too.
Without Authz I get a nice explanation of why my query is invalid:
```
Cannot query field \"token\" on type \"TokenPairOutputDto\".
```

With Authz I have no a very obscure error message, which gives no clue on what's going wrong.

```
Cannot read property 'args' of undefined
```

2022-09-09 10:15 UTC, XBeg9 commented
Hi @defond0 , this is a great contribution. Could you please add `changeset` ?

2022-09-09 10:25 UTC, XBeg9 requested changes

2022-09-09 10:25 UTC, XBeg9 commented on packages/core/src/rules-compiler.ts
> +        if (graphqlField===undefined){
```suggestion
        if (graphqlField === undefined){
```

2022-09-09 22:05 UTC, defond0 commented
> Hi @defond0 , this is a great contribution. Could you please add `changeset` ?

Pushed up the change requested, and a changeset.

2022-09-12 05:17 UTC, XBeg9 approved these changes

2022-09-12 05:46 UTC, XBeg9 requested changes

2022-09-12 05:46 UTC, XBeg9 commented on packages/core/src/rules-compiler.ts
> +          return undefined
```suggestion
          return undefined;
```

2022-09-12 05:46 UTC, XBeg9 commented on packages/core/src/rules-compiler.ts
> +          return undefined
sorry, could you please check if `prettier` CI valid

2022-09-12 05:55 UTC, XBeg9 approved these changes

2022-09-12 05:55 UTC, merged

2022-09-12 09:50 UTC, OoDeLally commented
Thanks guys :)

2022-09-12 11:06 UTC, XBeg9 commented
@OoDeLally could you please confirm the fix? :)

2022-09-12 12:16 UTC, OoDeLally commented
@XBeg9 Could you publish a new npm package?

2022-09-12 13:15 UTC, XBeg9 commented
hm, @OoDeLally it should be there already. https://www.npmjs.com/package/@graphql-authz/apollo-server-plugin

2022-09-14 07:57 UTC, OoDeLally commented
I can confirm this is fixed. Thanks guys! <3